# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dfa0bed118995b8b52c611f092e8ec8c3c652a6b4319437f811086f8c1eb28ca58bd1ac9d19bb5ebc780fd53a89a48d34c97cf3f696a70747d29d9fc7060a38

test:
  secret_key_base: 6296f9c600a38d25e6c62dfd0d1358d723eb046db328119f0075e609807b097b420c6ff114c0a452980c656d854008afbc4ffc7702c1dfc4d46507344021ec3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
